/**
 * One development/care tip per day of a baby's first 12 weeks, sourced from
 * official national health authorities and midwife bodies (not blogs or
 * generic parenting sites). `title` and `tip` are used as translation keys
 * via useLocalization()'s t() — see src/localization/translations/en.json.
 *
 * `day` 1-84 is the day of the baby's life (day 1 = birth day). The first
 * day of each week (day = (week-1)*7 + 1) is `isWeeklyFeature: true` and
 * carries the original weekly headline tip; the other six days of each
 * week are shorter daily tips that fill in the "daily" frequency setting.
 *
 * Currently covers days 1-84 (weeks 1-12). Later weeks are tracked as a
 * follow-up (GitHub issue) since each entry requires genuine verified
 * sourcing.
 */
export interface DailyTip {
  day: number;
  title: string;
  tip: string;
  sourceName: string;
  sourceUrl: string;
  sourceCountry: 'UK' | 'France' | 'Spain' | 'Denmark' | 'Germany' | 'Italy' | 'Netherlands' | 'Portugal' | 'Romania' | 'WHO';
  isWeeklyFeature: boolean;
}

export const DAILY_TIPS: DailyTip[] = [
  {
    day: 1,
    title: 'Watch for early hunger cues',
    tip: 'Newborns show they\'re hungry well before they cry — look for lip-smacking, stirring, sucking on their hands, or turning their head toward you. Crying is actually a late sign of hunger, so catching these earlier cues can make feeds calmer for you both. Breastfed babies typically feed 8-12 times in 24 hours, which is completely normal.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://cambspborochildrenshealth.nhs.uk/feeding-and-eating/feeding-cues-and-signs-of-getting-enough-milk/',
    sourceCountry: 'UK',
    isWeeklyFeature: true,
  },
  {
    day: 2,
    title: 'Skin-to-skin contact calms you both',
    tip: 'Holding your newborn skin-to-skin — against your bare chest, covered with a blanket — helps regulate their breathing, heart rate and temperature while lowering stress hormones for you both. It also releases oxytocin, which supports bonding and can make breastfeeding easier to establish. Try for it often in these early days, not just right after birth.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nbt.nhs.uk/maternity-services/feeding-your-baby/skin-skin',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 3,
    title: 'Let the umbilical cord stump dry naturally',
    tip: 'Keep your baby\'s umbilical cord stump clean, dry and outside the nappy area rather than covering it — fold the nappy down below it so air can reach it. There\'s no need for wipes, powders or creams; plain water is enough if it\'s soiled. It will usually dry up and fall off on its own within five to twelve days, so resist the urge to pull it off.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.mkuh.nhs.uk/patient-information-leaflet/care-of-the-umbilical-cord',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 4,
    title: 'Nappies tell you feeding is going well',
    tip: 'As a rough guide, your baby should have roughly as many wet nappies as they are days old for the first few days, rising to at least six heavy, wet nappies every 24 hours from about day five. Dirty nappies should also become more frequent and change from thick, dark meconium to a lighter, mustard-yellow colour by day four or five. If output seems low, tell your midwife — it\'s one of the clearest signs of how feeding is going.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/breastfeeding-and-bottle-feeding/breastfeeding-problems/enough-milk/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 5,
    title: 'The baby blues are common and pass',
    tip: 'Feeling weepy, anxious or on edge for a few days after birth is extremely common — it affects up to 80% of new mothers and usually starts around day three. Hormone changes, birth recovery and the sheer upheaval of a new baby all play a part, and it should ease within about two weeks without any treatment. If low feelings persist beyond two weeks or get worse, mention it to your midwife, health visitor or GP.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/conditions/baby/support-and-services/feeling-depressed-after-childbirth/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 6,
    title: 'Your newborn is already using every sense',
    tip: 'From birth, your baby is absorbing the world through sight, sound, smell, taste and touch, even though it\'s hard work for their still-developing nervous system. Their sight is blurry beyond about 30cm, but their hearing is well developed and they\'ll already recognise your voice. Keep introductions gentle — a calm environment helps them take it all in without becoming overwhelmed.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/pregnancy/labour-and-birth/after-the-birth/getting-to-know-your-newborn/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 7,
    title: 'A good latch makes breastfeeding easier',
    tip: 'Good positioning helps your baby attach effectively: keep them close with their head free to tilt back, body in a straight line, and their nose level with your nipple. A wide-open mouth with more of the darker skin visible above their top lip than below is a sign of a good latch. If feeding is painful beyond the first few seconds, ask your midwife or a breastfeeding supporter to check the latch.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/breastfeeding-and-bottle-feeding/breastfeeding/positioning-and-attachment/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 8,
    title: 'Jaundice and crying are usually normal',
    tip: 'Many newborns turn slightly yellow (jaundice) around day 3, and it usually fades on its own within a couple of weeks — mention it to your midwife if it lasts longer or your baby seems unwell. It\'s also completely normal for a young baby to cry, on and off, for up to two hours a day. If you\'re ever worried, trust your instinct and call your health visitor or GP.',
    sourceName: 'AEPED (Spain)',
    sourceUrl: 'https://www.aeped.es/enfamilia/salud-en-familia/cosas-normales-en-recien-nacidos',
    sourceCountry: 'Spain',
    isWeeklyFeature: true,
  },
  {
    day: 9,
    title: 'Burping helps release trapped air',
    tip: 'Swallowed air can make your baby uncomfortable, so pause during or after feeds to burp them — there\'s no strict rule about timing, just watch for squirming or pulling off. Support their head and neck, keep their back straight rather than curled, and gently pat or rub for a minute or two. If wind seems trapped despite burping, lay them on their back and gently massage their tummy.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/best-start-in-life/baby/feeding-your-baby/breastfeeding/how-to-breastfeed/burping-your-baby/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 10,
    title: 'You don\'t need to bathe daily',
    tip: 'Newborns don\'t need a bath every day — two or three times a week is plenty, and \'topping and tailing\' (washing face, hands, neck and bottom) works well in between. Plain water is best for their skin in the first month; save lotions and oils until they\'re at least a month old. If your baby enjoys bath time, though, there\'s no harm in doing it daily.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/caring-for-a-newborn/washing-and-bathing-your-baby/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 11,
    title: 'The heel prick test screens for rare conditions',
    tip: 'Around day five, a midwife or health visitor will take a few drops of blood from your baby\'s heel to screen for ten rare but serious conditions. Catching these early means treatment can start sooner, improving long-term outcomes, and there are no known risks to your baby from the test itself. Feeding and cuddling your baby beforehand can help keep them settled.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/newborn-screening/blood-spot-test/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 12,
    title: 'Start tummy time in tiny bursts',
    tip: 'You can begin tummy time from birth simply by laying your baby on your chest while you\'re wide awake — little and often is the way to start. Aim for just one or two minutes at a time to begin with, building up gradually as they get stronger. Always stay with them, and avoid doing it right after a feed.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/best-start-in-life/baby/baby-moves/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 13,
    title: 'Rear-facing car seats keep travel safe',
    tip: 'The safest way for your baby to travel is rear-facing, in a UK-approved car seat fitted with the adult seatbelt, ideally in the back seat. Avoid journeys longer than two hours at a stretch, as extended time in a car seat has been linked to breathing difficulties in young babies. Once you arrive, take them out and transfer a sleeping baby to a flat, firm surface rather than leaving them in the seat.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/first-aid-and-safety/safety/choosing-a-baby-car-seat/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 14,
    title: 'Fathers and partners build bonds too',
    tip: 'Bonding isn\'t just a mother\'s job — babies build a secure attachment with any caregiver who responds consistently to their needs. For fathers and partners, everyday moments like bathing, carrying, and soothing your baby all help strengthen that connection from these very first weeks. The more time you spend close to your baby now, the more naturally that closeness grows.',
    sourceName: 'BZgA / familienplanung.de (Germany)',
    sourceUrl: 'https://www.familienplanung.de/schwangerschaft/nach-der-geburt/die-ersten-tage/bindung-ein-grundbeduerfnis/',
    sourceCountry: 'Germany',
    isWeeklyFeature: false,
  },
  {
    day: 15,
    title: 'How much sleep is normal at this age',
    tip: 'Babies aged 0-3 months are recommended to sleep around 14-17 hours a day, though anywhere from 11 to 19 hours can still be normal for an individual baby. Don\'t worry about hitting an exact number, especially in the very first days after birth when longer sleep is expected. Every baby settles into their own rhythm at their own pace.',
    sourceName: 'Sundhedsstyrelsen (Denmark)',
    sourceUrl: 'https://www.sst.dk/vidensbase/forebyggelse/anbefalinger-for-soevnlaengde',
    sourceCountry: 'Denmark',
    isWeeklyFeature: true,
  },
  {
    day: 16,
    title: 'Cluster feeding is normal, not a problem',
    tip: 'You may notice your baby wanting to feed almost constantly for a day or two, often in the evenings — this is called cluster feeding and it\'s especially common during growth spurts in the first few months. It helps boost your milk supply to match your baby\'s growing needs, so try to go with it rather than worry. Once supply catches up, feeding usually settles back into a more predictable pattern.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/best-start-in-life/baby/feeding-your-baby/bottle-feeding/bottle-feeding-your-baby/cluster-feeding/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 17,
    title: 'Your baby already knows your voice and smell',
    tip: 'Long before they can see you clearly, your baby is learning to recognise you by your voice, smell and touch — cues that helped calm them even in the womb. Talking softly, holding them close and making eye contact when you can all reinforce this sense of safety. These small, repeated moments are what build trust in these early weeks.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/pregnancy/labour-and-birth/after-the-birth/getting-to-know-your-newborn/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 18,
    title: 'Dummies may help, once feeding is settled',
    tip: 'There\'s some evidence that offering a dummy at the start of sleep may lower the risk of SIDS, though experts don\'t all agree on promoting it. If you\'re breastfeeding, it\'s best to wait until feeding is well established — usually around a month — before introducing one, so it doesn\'t interfere with latch or supply. If you do use one, offer it every time your baby settles for sleep, day or night.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/conditions/baby/caring-for-a-newborn/reduce-the-risk-of-sudden-infant-death-syndrome/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 19,
    title: 'Postnatal depression can start these weeks',
    tip: 'Unlike the baby blues, postnatal depression tends to develop over the first six weeks and doesn\'t simply pass on its own — signs include persistent low mood, losing interest in things you\'d normally enjoy, and struggling to look after yourself or your baby. It\'s very treatable, and speaking to your GP, midwife or health visitor early makes a real difference. You won\'t be judged, and asking for help is a sign of strength, not failure.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/mental-health/conditions/postnatal-depression/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 20,
    title: 'Your baby\'s vision is coming into focus',
    tip: 'At birth your baby\'s sight is the least developed of their senses, but it sharpens quickly — by around a month they can start focusing on objects close to their face, and by three months many can fix their gaze on faces and follow a moving object. Hold things and your face around 20-30cm away during alert moments to give them plenty to look at. This is also a great time for simple, high-contrast toys or books.',
    sourceName: 'AEPED (Spain)',
    sourceUrl: 'https://www.aeped.es/enfamilia/multimedia/desarrollo-visual-bebe',
    sourceCountry: 'Spain',
    isWeeklyFeature: false,
  },
  {
    day: 21,
    title: 'Keep the nursery a little cooler than feels cosy',
    tip: 'An ideal room temperature for sleep is 16-20C, which can feel surprisingly cool — a room thermometer takes the guesswork out of it. Babies who get too hot are at higher risk of SIDS, so dress them in light layers and a well-fitting sleep bag rather than loose blankets. Check by feeling their chest or the back of their neck, not their hands or feet, which are naturally cooler.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/best-start-in-life/baby/baby-basics/newborn-and-baby-sleeping-advice-for-parents/safe-sleep-advice-for-babies/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 22,
    title: 'Reduce the risk of SIDS',
    tip: 'Always put your baby to sleep on their back, in their own cot or Moses basket, in the same room as you for at least the first six months, including for naps. Keep their feet at the end of the cot (\'feet to foot\'), avoid loose blankets or cushions, and keep the room between 16-20C. Never smoke around your baby, and keep vaccinations on schedule — all of this lowers the risk of sudden infant death syndrome.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/caring-for-a-newborn/sudden-infant-death-syndrome-sids/',
    sourceCountry: 'UK',
    isWeeklyFeature: true,
  },
  {
    day: 23,
    title: 'Prepare formula feeds one at a time',
    tip: 'If you\'re formula feeding, make up each feed fresh using water that\'s been boiled and cooled for no more than 30 minutes, adding the water to the bottle before the powder. Always use the exact amount of powder stated on the packaging, and cool the bottle under cold running water until it\'s just body temperature — test it on your wrist. Throw away any formula left over after a feed rather than saving it.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/breastfeeding-and-bottle-feeding/bottle-feeding/making-up-baby-formula/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 24,
    title: 'It’s OK to put your baby down and step away',
    tip: 'Crying tends to peak around this age and can be exhausting to sit with — if you\'re feeling overwhelmed and your baby is safe in their cot, it\'s fine to step into another room for a few minutes to calm down before going back. No matter how frustrated you feel, never shake your baby, as it can cause serious brain injury. If the crying feels like too much, call a friend, your health visitor, or a helpline like Cry-sis.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/caring-for-a-newborn/soothing-a-crying-baby/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 25,
    title: 'Newborn reflexes are doing important work',
    tip: 'Your baby\'s sucking and grasping reflexes are automatic at this age — stroke their palm and their fingers will close around yours with surprising strength. The sucking reflex intensifies over the coming weeks before becoming a deliberate, voluntary action around six months. These reflexes are checked at your baby\'s newborn exam because they\'re a good early sign of healthy neurological development.',
    sourceName: 'AEPED (Spain)',
    sourceUrl: 'https://enfamilia.aeped.es/edades-etapas/cuidados-bebe-recien-nacido',
    sourceCountry: 'Spain',
    isWeeklyFeature: false,
  },
  {
    day: 26,
    title: 'Book your postnatal check for around 6 weeks',
    tip: 'Around six to eight weeks after birth, your GP surgery should offer you a postnatal check covering your physical recovery and your emotional wellbeing, alongside a separate check for your baby\'s eyes, heart, hips, weight and growth. It\'s a good moment to raise anything that\'s been worrying you, including mood, healing, or contraception. The two appointments can be booked together or separately, whichever suits you.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/support-and-services/your-6-week-postnatal-check/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 27,
    title: 'Handwashing protects your still-vulnerable baby',
    tip: 'Your baby\'s immune system is still immature, so good hand hygiene from you and any visitors is one of the simplest ways to reduce their risk of picking up an infection. Ask anyone with a cold, cough, vomiting or diarrhoea to wait until they\'re well before holding your baby. It\'s completely reasonable to ask visitors to wash their hands first — most people expect it.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.hey.nhs.uk/patient-leaflet/protecting-your-baby-from-infection/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 28,
    title: 'Feed on demand, not by the clock',
    tip: 'Responsive feeding — offering the breast or bottle whenever your baby shows hunger cues, rather than sticking to a strict schedule — helps establish supply and reassures your baby that comfort is always available. There\'s no need to count hours between feeds at this age; let your baby\'s cues lead. It also works both ways: responding to their fullness cues helps them learn to stop when satisfied.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://cambspborochildrenshealth.nhs.uk/feeding-and-eating/responsive-feeding/responsive-breastfeeding/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 29,
    title: 'Vitamin D drops from two weeks',
    tip: 'From two weeks of age, babies are recommended a daily vitamin D supplement (10 micrograms, about 5 drops) up until age four, since it\'s hard to get enough from sunlight and diet alone. If your baby has at least 800ml of infant formula a day, they\'re already getting enough and don\'t need extra drops. Ask your health visitor if you\'re unsure which applies to your baby.',
    sourceName: 'Sundhedsstyrelsen (Denmark)',
    sourceUrl: 'https://www.sst.dk/vidensbase/graviditet-og-smaaboern/kost-til-smaaboern/d-vitamin-og-jerntilskud-til-boern',
    sourceCountry: 'Denmark',
    isWeeklyFeature: true,
  },
  {
    day: 30,
    title: 'Eat well while breastfeeding, iron included',
    tip: 'There\'s no special supplement routine required for breastfeeding mothers beyond following general healthy-eating advice, but it\'s worth paying attention to iron-rich foods like meat, beans and leafy greens, ideally paired with vitamin C-rich fruit or veg to help absorption. A varied, balanced diet supports both your energy levels and your milk. If you\'re vegetarian or have specific dietary restrictions, ask your health visitor or GP about whether a supplement makes sense for you.',
    sourceName: 'Sundhedsstyrelsen (Denmark)',
    sourceUrl: 'https://www.sst.dk/vidensbase/graviditet-og-smaaboern/graviditet/ernaering-mad-og-maaltider-til-gravide-og-ammende/amning',
    sourceCountry: 'Denmark',
    isWeeklyFeature: false,
  },
  {
    day: 31,
    title: 'A calm environment helps sleep develop',
    tip: 'Your baby doesn\'t yet have an adult sleep rhythm, but you can start nudging them toward one by keeping night feeds and changes calm, quiet and dimly lit, while daytime stays brighter and more active. A simple, repeated pre-sleep routine — even just a cuddle and a few quiet words — helps signal that sleep is coming. It won\'t produce a full night\'s sleep yet, but it lays useful groundwork.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/caring-for-a-newborn/helping-your-baby-to-sleep/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 32,
    title: 'A little spit-up after feeds is common',
    tip: 'Reflux — bringing up small amounts of milk during or after a feed — is very common under a year old and isn\'t a concern as long as your baby is happy, feeding well and gaining weight. It usually starts before eight weeks and improves by their first birthday. Contact your GP or health visitor if your baby seems distressed, refuses feeds, or isn\'t gaining weight as expected.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/conditions/reflux-in-babies/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 33,
    title: 'Tummy time strength builds week by week',
    tip: 'By now you can start building up tummy time from those first one-to-two-minute bursts toward ten to fifteen minutes spread across the day. Some babies protest at first, and that\'s completely normal — plenty of praise and short, frequent sessions help them get used to it. You\'ll likely start noticing them lifting their head a little higher each week.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/best-start-in-life/baby/baby-moves/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 34,
    title: 'Baby massage can soothe and connect',
    tip: 'Gentle, rhythmic massage with a plain, natural oil can help with common issues like wind and mild constipation, and may even help your baby settle to sleep. Beyond the physical benefits, it\'s a lovely one-to-one moment that supports feelings of closeness and trust — and it\'s particularly helpful for parents managing low mood or anxiety. Choose a warm room, keep sessions short, and stop if your baby seems unsettled by it.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.justonenorfolk.nhs.uk/pregnancy-early-days/new-baby/baby-massage/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 35,
    title: 'Ease back into exercise gently',
    tip: 'If you had a straightforward birth, gentle activity like walking, stretching and pelvic floor exercises can usually start as soon as you feel ready — but hold off on anything high-impact, like running, until after your six-week check and ideally closer to three months. If your birth was more complicated or you had a caesarean, check with your midwife or GP before starting anything strenuous. Your joints and ligaments stay more flexible than usual for a few months, so ease in slowly.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/support-and-services/keeping-fit-and-healthy-with-a-baby/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 36,
    title: 'Colic often peaks around six weeks',
    tip: 'If your baby has bouts of intense crying lasting three hours or more, it may be colic — very common, and it usually eases by 3-4 months. Try holding your baby upright after feeds to help bring up wind, gentle clockwise tummy massage, or \'bicycling\' their legs. Responding early with a feed or cuddle helps more than any product on the shelf — most colic remedies work no better than a placebo.',
    sourceName: 'AEPED (Spain)',
    sourceUrl: 'https://www.aeped.es/enfamilia/salud-en-familia/colicos-lactante',
    sourceCountry: 'Spain',
    isWeeklyFeature: true,
  },
  {
    day: 37,
    title: 'Know the signs of mastitis',
    tip: 'A tender, red or hot patch on your breast, sometimes with flu-like aches and a raised temperature, can be a sign of mastitis, usually caused by a blocked milk duct that hasn\'t cleared. Keep breastfeeding on that side as normal — this actually helps, rather than making things worse — and try feeding in different positions to help drain the duct. Contact your GP or NHS 111 if you\'re not feeling better within 12 to 24 hours, as antibiotics are sometimes needed.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/best-start-in-life/baby/feeding-your-baby/breastfeeding/breastfeeding-challenges/mastitis/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 38,
    title: 'Using a sling? Remember the TICKS rule',
    tip: 'If you use a baby carrier or sling, the TICKS rule is a handy safety check: Tight, In view at all times, Close enough to kiss, Keep chin off chest, and Supported back. There should always be at least a finger\'s width of space under your baby\'s chin, and the fabric should never cover their face. Never feed your baby while they\'re in a sling — take them out first.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.walsallhealthcare.nhs.uk/wp-content/uploads/2023/03/TICKS-Guidance-for-wearing-baby-sling.pdf',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 39,
    title: 'A follow-up hearing check may happen now',
    tip: 'If your baby\'s newborn hearing screen didn\'t give a clear result in one or both ears, a follow-up appointment with an audiology specialist would usually happen within about four weeks — so this may be around now for some babies. Most babies who need a second test turn out to hear just fine; it\'s simply a more detailed check. If you have any concerns about your baby\'s response to sound at any point, you can always ask your health visitor for a referral.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/newborn-screening/hearing-test/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 40,
    title: 'Ask for support before you reach breaking point',
    tip: 'It\'s completely normal to feel overwhelmed by six weeks in, and asking for help early — rather than waiting until things feel unmanageable — makes a real difference. Support can be practical as much as emotional: a family midwife, a parent-child group, or simply a relative taking the baby for an hour so you can rest. These services exist precisely for ordinary struggles with crying, sleep and feeling exhausted, not just emergencies.',
    sourceName: 'Frühe Hilfen / kindergesundheit-info.de (Germany)',
    sourceUrl: 'https://www.kindergesundheit-info.de/themen/entwicklung/0-12-monate/fruehe-hilfen-fuer-eltern/',
    sourceCountry: 'Germany',
    isWeeklyFeature: false,
  },
  {
    day: 41,
    title: 'Test bath water with your elbow',
    tip: 'Before every bath, check the water temperature with your elbow rather than your hand — it should feel comfortably warm, roughly body temperature, with no hot patches after mixing. Never leave your baby alone in the bath, even for a moment, and keep the bathroom warm and draught-free. A bath thermometer can help take the guesswork out of it if you\'d like extra reassurance.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/best-start-in-life/baby/baby-basics/caring-for-your-baby/bathing-your-baby/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 42,
    title: 'Try putting your baby down drowsy, not asleep',
    tip: 'When your baby seems sleepy but is still awake, try putting them down in their cot rather than waiting until they\'re fully asleep in your arms. Over time, this helps them learn to settle themselves, which can make it easier for them to drift back off after natural night wakings. It won\'t work every time, and that\'s fine — consistency over weeks matters more than any single night.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/caring-for-a-newborn/helping-your-baby-to-sleep/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 43,
    title: 'Always put baby down on their back',
    tip: 'Lay your baby flat on their back on a firm mattress, with nothing loose in the cot — no pillow, blanket, bumper or soft toy. For at least the first six months, it\'s safer to keep their crib in your own bedroom. Watch for your baby\'s tired signs and put them down as soon as you notice them, rather than waiting until they\'re overtired.',
    sourceName: 'Santé publique France (1000 premiers jours)',
    sourceUrl: 'https://www.1000-premiers-jours.fr/fr/le-sommeil-de-bebe',
    sourceCountry: 'France',
    isWeeklyFeature: true,
  },
  {
    day: 44,
    title: 'Room-sharing lowers SIDS risk',
    tip: 'Keeping your baby\'s cot or Moses basket in your bedroom for at least the first six months, for both day naps and night sleep, is one of the clearest ways to reduce the risk of SIDS. This doesn\'t mean bed-sharing — a separate, flat sleep surface next to your bed is safest. It also makes night feeds and checks easier while you\'re both adjusting.',
    sourceName: 'Santé publique France (1000 premiers jours)',
    sourceUrl: 'https://www.1000-premiers-jours.fr/fr/le-sommeil-de-bebe',
    sourceCountry: 'France',
    isWeeklyFeature: false,
  },
  {
    day: 45,
    title: 'There’s no need for a strict feeding schedule yet',
    tip: 'At this age, following your baby\'s hunger and fullness cues generally works better than trying to impose a fixed schedule between feeds. Babies naturally start to develop more predictable feeding patterns over the coming weeks as their stomachs grow and they take more per feed. Trust that responsive feeding is doing its job, even when the gaps between feeds still look uneven.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://cambspborochildrenshealth.nhs.uk/feeding-and-eating/responsive-feeding/responsive-breastfeeding/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 46,
    title: 'Look out for your baby\'s first real smile',
    tip: 'Somewhere between six and eight weeks, many babies start to smile socially — a deliberate smile in response to your face or voice, rather than the reflexive smiles seen earlier. It\'s a meaningful step in their social and emotional development, and a sign their nervous system is maturing well. Smile and talk to them often; they\'re learning that their own expressions get a warm response back.',
    sourceName: 'AEPED (Spain)',
    sourceUrl: 'https://www.aeped.es/enfamilia/salud-en-familia/bebe-2-4-meses',
    sourceCountry: 'Spain',
    isWeeklyFeature: false,
  },
  {
    day: 47,
    title: 'Partners can experience postnatal depression too',
    tip: 'It\'s not only birthing parents who can develop postnatal depression — around one in five partners experience low mood, anxiety or depression after a baby arrives, and rates are higher when they\'re also supporting a partner through a difficult time. The signs can look similar: low mood, irritability, withdrawal, or feeling unable to cope. It\'s just as important for partners to talk to a GP or health visitor if these feelings don\'t lift.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/mental-health/conditions/postnatal-depression/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 48,
    title: 'Keep young babies out of direct sun',
    tip: 'Babies under six months should be kept out of direct, strong sunlight altogether rather than relying on sunscreen, which isn\'t recommended at this age. Use a parasol or sunshade on the pram to create shade, and dress them in lightweight, loose clothing rather than piling on layers. Never cover a pram with a blanket to block the sun — it can trap heat and cause overheating.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/first-aid-and-safety/safety/safety-in-the-sun/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 49,
    title: 'Enjoy the longer awake, alert stretches',
    tip: 'Around this age, many babies start having longer stretches of calm, alert wakefulness — a great window for face-to-face play, gentle chat, and simple games like slowly moving your face side to side for them to follow. These interactions are how your baby practises early social skills like eye contact and turn-taking. Watch for tired signs, though, as overtired babies can become harder to settle.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/pregnancy/labour-and-birth/after-the-birth/getting-to-know-your-newborn/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 50,
    title: 'First vaccinations at 8 weeks',
    tip: 'At 8 weeks old, your baby is due their first big round of vaccinations: the 6-in-1 jab (protecting against diphtheria, hepatitis B, Hib, polio, tetanus and whooping cough), plus the MenB and rotavirus vaccines. It\'s normal for babies to be a little unsettled or feverish afterwards — your GP or health visitor can advise on infant paracetamol if needed. These vaccines protect your baby during a period when they\'re most vulnerable to serious infection.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/vaccinations/6-in-1-vaccine/',
    sourceCountry: 'UK',
    isWeeklyFeature: true,
  },
  {
    day: 51,
    title: 'A little fever after vaccines is normal',
    tip: 'It\'s common for babies to be a bit unsettled or develop a mild fever for a day or two after their 8-week vaccinations — it\'s a sign their immune system is responding. For the MenB vaccine specifically, giving infant liquid paracetamol shortly after, then further doses 4-6 hours apart (up to three doses in 24 hours), can help prevent a high temperature. If the fever hasn\'t settled after 48 hours, or you\'re worried, call your GP or NHS 111.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/vaccinations/vaccination-tips-for-parents/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 52,
    title: 'Your baby\'s 6-8 week check covers a lot',
    tip: 'At your baby\'s 6-8 week check, the GP will look at their eyes, heart, hips and (for boys) testicles, and measure their weight, length and head circumference to track growth. It\'s a good opportunity to raise anything you\'ve noticed, even small things — there\'s no such thing as too minor a question at this appointment. This check can often be booked alongside your own postnatal check for convenience.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/support-and-services/your-6-week-postnatal-check/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 53,
    title: 'You can combine breast and bottle if it suits you',
    tip: 'Once breastfeeding is well established — usually from six to eight weeks — many parents choose to offer some bottles of expressed milk or formula alongside breastfeeding. It\'s worth knowing that introducing bottles can affect your milk supply and how your baby sucks, so go at a pace that works for you rather than switching abruptly. The National Breastfeeding Helpline can talk through the options if you\'re unsure.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/breastfeeding-and-bottle-feeding/bottle-feeding/combine-breast-and-bottle/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 54,
    title: 'Watch your baby\'s eyes start tracking objects',
    tip: 'Between two and four months, many babies get noticeably better at following a moving object with their eyes and reaching or swiping toward things nearby. Slowly moving a bright toy or your face in front of them is a simple way to encourage this. It\'s an early building block for the hand-eye coordination they\'ll rely on for reaching and grasping in the months ahead.',
    sourceName: 'AEPED (Spain)',
    sourceUrl: 'https://www.aeped.es/enfamilia/multimedia/desarrollo-visual-bebe',
    sourceCountry: 'Spain',
    isWeeklyFeature: false,
  },
  {
    day: 55,
    title: 'Vary your baby\'s head position often',
    tip: 'Babies\' skulls are soft and can flatten on one side if they spend too long in the same position, whether sleeping, in a car seat, or being carried. Alternate which arm you hold them in, change the side you feed from, and vary where toys and mobiles are placed to encourage them to turn their head both ways. Plenty of supervised tummy time while awake also helps take pressure off the back of the head.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/conditions/flat-head-syndrome-plagiocephaly-brachycephaly/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 56,
    title: 'Rest when you can, even briefly',
    tip: 'Sleep deprivation catches up with most new parents around now — try to rest when your baby sleeps rather than using every gap for chores, and ask your partner or family to take a shift so you can nap or just lie down. Even five to ten minutes of proper rest can help, and a short daily walk can leave you feeling less drained than staying in. If exhaustion doesn\'t lift even when you do get a chance to sleep, mention it to your health visitor or GP, as it can be a sign of something more.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/support-and-services/sleep-and-tiredness-after-having-a-baby/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 57,
    title: 'Your baby is learning to organise sleep',
    tip: 'Newborns don\'t yet have an adult day/night rhythm, but over these early weeks your baby gradually starts learning to tell day from night. You can help by keeping things calm and dim at night and brighter or louder during the day, and by keeping routines like bath time around the same time each day. It won\'t produce a full night\'s sleep yet, but it lays the groundwork.',
    sourceName: 'AEPED (Spain)',
    sourceUrl: 'https://www.aeped.es/enfamilia/salud-en-familia/el-sueno-en-el-recien-nacido',
    sourceCountry: 'Spain',
    isWeeklyFeature: true,
  },
  {
    day: 58,
    title: 'Trust that on-demand feeding is working',
    tip: 'If your baby is feeding whenever they show hunger cues, it\'s almost never the case that they\'re not getting enough — babies are generally very good at regulating their own intake this way. Continuing to breastfeed exclusively through these early months, alongside all the other adjustments of new parenthood, brings real benefits for both of you. If you ever want reassurance, weight checks with your health visitor are the most reliable way to confirm feeding is on track.',
    sourceName: 'SNS (Portugal)',
    sourceUrl: 'https://www.sns.gov.pt/noticias/2020/08/03/semana-mundial-do-aleitamento-materno-3/',
    sourceCountry: 'Portugal',
    isWeeklyFeature: false,
  },
  {
    day: 59,
    title: 'Listen for your baby\'s first coos',
    tip: 'Somewhere around two to four months, babies begin cooing and experimenting with early sounds like \'ba\' and \'da\', a first step toward spoken language. They\'re also starting to grasp that speech carries emotion and meaning, even before they understand actual words. Responding to their sounds with words of your own — a real back-and-forth — helps this development along.',
    sourceName: 'Santé publique France (1000 premiers jours)',
    sourceUrl: 'https://www.1000-premiers-jours.fr/fr/le-developpement-du-langage-de-bebe',
    sourceCountry: 'France',
    isWeeklyFeature: false,
  },
  {
    day: 60,
    title: 'Keep small objects out of reach',
    tip: 'As your baby becomes more active with their hands, it\'s worth checking floors and low surfaces for anything smaller than about 4.5cm across — buttons, coins, small toy parts and deflated balloons are all choking risks. Button batteries are especially dangerous if swallowed, so keep them well out of reach. It\'s a good moment to start thinking a step ahead of your baby\'s growing mobility.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/first-aid-and-safety/safety/baby-and-toddler-safety/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 61,
    title: 'It\'s never too early to read together',
    tip: 'Reading to your baby, even at this age, supports bonding, voice recognition and early language development — they won\'t follow the story, but they\'ll enjoy your voice, rhythm and closeness. Over time, babies who are read to regularly tend to develop speech and reading skills sooner. A few minutes with a simple board book, at any point in the day, is plenty to start with.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.emnodn.nhs.uk/readingtoyourbaby',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 62,
    title: 'A consistent wind-down helps sleep',
    tip: 'Starting a simple, repeated bedtime routine — a bath, a quiet cuddle, a few soft words — around the same time each evening helps your baby begin to associate these steps with sleep. Try to keep the room calm and avoid too much stimulation in the half hour before bed. Consistency matters more than any particular routine, so pick something manageable and stick with it.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/caring-for-a-newborn/helping-your-baby-to-sleep/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 63,
    title: 'Look after your relationship, not just the baby',
    tip: 'It\'s easy for a couple\'s relationship to take a back seat once a baby arrives, but small things — sharing night feeds and nappy changes, checking in on how the other person is really doing, making a little time for each other — go a long way. Be explicit about what you need, whether that\'s a hug or simply being listened to, since even a close partner can\'t read your mind right now. If things feel like they\'re struggling, relationship support and counselling are there to help, not just for crises.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/support-and-services/relationships-after-having-a-baby/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 64,
    title: 'New skills: cooing and lifting their head',
    tip: 'Around two months, many babies start cooing and reacting to your voice, show early emotions like joy or frustration, and briefly lift their head and shoulders during tummy time. They may also start swiping at or grasping nearby objects. Treat this as a rough guide, not a checklist — every baby moves through these at their own pace.',
    sourceName: 'Santé publique France (1000 premiers jours)',
    sourceUrl: 'https://www.1000-premiers-jours.fr/fr/les-etapes-du-developpement-de-bebe',
    sourceCountry: 'France',
    isWeeklyFeature: true,
  },
  {
    day: 65,
    title: 'Expressed milk gives you flexibility',
    tip: 'Expressing milk, by hand or with a pump, lets someone else offer a feed while you get a break, or lets you build a small stash for when you\'re apart from your baby. Freshly expressed milk can go in the fridge for use within a few days, or the freezer for longer storage. Whichever method feels most comfortable is the right one — there\'s no single correct way to express.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/breastfeeding-and-bottle-feeding/breastfeeding/expressing-breast-milk/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 66,
    title: 'Watch your baby start to reach and swipe',
    tip: 'Around this age, many babies get better at coordinating their eyes and hands, following a moving object and then reaching or batting at it. It\'s an early, clumsy version of the hand-eye coordination they\'ll use for grasping toys in the coming weeks. Dangling a toy just within reach during alert, playful moments gives them good practice.',
    sourceName: 'AEPED (Spain)',
    sourceUrl: 'https://www.aeped.es/enfamilia/multimedia/desarrollo-visual-bebe',
    sourceCountry: 'Spain',
    isWeeklyFeature: false,
  },
  {
    day: 67,
    title: 'Never leave your baby unattended on a raised surface',
    tip: 'Babies can begin wriggling and pushing more strongly than you\'d expect at this age, so never leave them alone on a changing table, sofa or bed, even for a moment — keep one hand on them or put them safely on the floor instead. The same goes for car seats or bouncers left on tables or counters. A few seconds is all it takes for a fall.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/first-aid-and-safety/safety/baby-and-toddler-safety/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 68,
    title: 'Skin-to-skin still matters after the newborn stage',
    tip: 'Skin-to-skin contact isn\'t just for the first hours after birth — continuing it in these early months keeps supporting bonding, calmer breathing and heart rate, and lower stress hormones for both of you. It\'s a lovely activity for partners to share too, not just the parent who gave birth. A few quiet minutes of skin contact can be a nice way to reconnect after a stretch apart.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nbt.nhs.uk/maternity-services/feeding-your-baby/skin-skin',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 69,
    title: 'Daytime naps are part of healthy sleep',
    tip: 'Babies this age typically still need several daytime sleep periods on top of nighttime sleep, so don\'t worry if naps still take up a good part of the day. A predictable rhythm — awake, feed, play, sleep — tends to work better than watching the clock. Some babies nap easily anywhere, while others need a calmer, dimmer space; both are normal.',
    sourceName: 'Sundhed.dk (Denmark)',
    sourceUrl: 'https://www.sundhed.dk/borger/patienthaandbogen/boern/om-boern/det-nyfoedte-barn/babyer-og-soevn/',
    sourceCountry: 'Denmark',
    isWeeklyFeature: false,
  },
  {
    day: 70,
    title: 'Tiredness this deep deserves real rest',
    tip: 'If broken sleep is leaving you feeling constantly exhausted, try going to bed early for a stretch of nights, and don\'t be afraid to ask your partner or a relative to take an early feed or two so you can get an unbroken block of sleep. A short daily walk, even just to the shops, can help more than it seems it would. If you\'re tired even after sleep, or struggling to cope, that\'s worth mentioning to your GP or health visitor.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/support-and-services/sleep-and-tiredness-after-having-a-baby/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 71,
    title: 'Talk and sing face-to-face with your baby',
    tip: 'Your baby\'s hearing is checked in the first weeks of life, and from birth they\'re already tuning into your voice. Try to get face-to-face with your baby when you talk, sing the same songs and rhymes over and over, and respond warmly when they make sounds — this back-and-forth is how they learn to make sounds themselves. Ask your health visitor if you have any concerns about your baby\'s hearing or responses to sound.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/best-start-in-life/baby/learning-to-talk/first-sounds-0-to-6-months/',
    sourceCountry: 'UK',
    isWeeklyFeature: true,
  },
  {
    day: 72,
    title: 'Feed on demand and trust the process',
    tip: 'If you\'re feeding your baby whenever they show hunger cues, it\'s rare for them not to be getting enough — babies are generally good at asking for what they need. Around six wet nappies and a healthy pattern of weight gain remain the best signs that feeding is going well. If you ever want reassurance, your health visitor can check your baby\'s growth against their own curve, not just averages.',
    sourceName: 'Voedingscentrum (Netherlands)',
    sourceUrl: 'https://www.voedingscentrum.nl/nl/zwanger-en-kind/borstvoeding-en-flesvoeding/borstvoeding-geven/hoeveel-borstvoeding-heeft-mijn-baby-nodig-.aspx',
    sourceCountry: 'Netherlands',
    isWeeklyFeature: false,
  },
  {
    day: 73,
    title: 'Reflexive grasping is turning voluntary',
    tip: 'Early on, your baby\'s grasp reflex meant their fingers closed automatically around anything placed in their palm. Around now, that reflex starts fading and more deliberate, voluntary reaching and grasping begins to take over — a sign their brain and muscles are coordinating in new ways. Offering a light rattle or textured toy within easy reach is a nice way to encourage this.',
    sourceName: 'AEPED (Spain)',
    sourceUrl: 'https://enfamilia.aeped.es/edades-etapas/cuidados-bebe-recien-nacido',
    sourceCountry: 'Spain',
    isWeeklyFeature: false,
  },
  {
    day: 74,
    title: 'Double-check sling safety as outings increase',
    tip: 'As you get out and about more, it\'s worth re-checking sling safety with the TICKS rule: Tight, In view, Close enough to kiss, Keep chin off chest, Supported back. Never let the fabric ride up over your baby\'s face, and take them out of the sling before feeding rather than feeding them inside it. A snug, upright carry is safest and most comfortable for both of you on longer trips.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.walsallhealthcare.nhs.uk/wp-content/uploads/2023/03/TICKS-Guidance-for-wearing-baby-sling.pdf',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 75,
    title: 'Night waking at this age is still normal',
    tip: 'Even as your baby\'s sleep matures, waking once or twice a night to feed is still completely normal around three months, and doesn\'t mean anything is wrong with their sleep. A settled day-night rhythm tends to develop gradually over these weeks rather than all at once. Try not to compare your baby\'s nights to others\' — the range of normal is wide.',
    sourceName: 'Sundhed.dk (Denmark)',
    sourceUrl: 'https://www.sundhed.dk/borger/patienthaandbogen/boern/om-boern/det-nyfoedte-barn/babyer-og-soevn/',
    sourceCountry: 'Denmark',
    isWeeklyFeature: false,
  },
  {
    day: 76,
    title: 'Everyday moments build a father\'s bond too',
    tip: 'Bathing, carrying, playing and soothing your baby are all ways fathers and partners build a close bond, just as effectively as a birthing parent does through feeding. This bonding period lasts through most of the first year, and it shapes how secure and trusting your child feels in relationships later on. Look for small windows each day — a nappy change, a walk, bedtime — to make this connection part of the routine.',
    sourceName: 'BZgA / familienplanung.de (Germany)',
    sourceUrl: 'https://www.familienplanung.de/schwangerschaft/nach-der-geburt/die-ersten-tage/bindung-ein-grundbeduerfnis/',
    sourceCountry: 'Germany',
    isWeeklyFeature: false,
  },
  {
    day: 77,
    title: 'Your body is still recovering, and that\'s fine',
    tip: 'By three months, it\'s easy to feel pressure to be \'back to normal\', but physical recovery from pregnancy and birth genuinely takes longer than that for most people. Be patient with yourself about energy levels, body changes and how you\'re feeling — there\'s no fixed timeline. If anything about your recovery is worrying you, your GP or health visitor can talk it through, even this far postpartum.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/support-and-services/your-post-pregnancy-body/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 78,
    title: 'Around three months: smiles and steadier head control',
    tip: 'By around three months, many babies hold their head up more steadily, move all four limbs more symmetrically, and reward you with real social smiles. They\'re also getting better at expressing emotions and recognising familiar faces and voices. If your baby isn\'t showing any of these signs at all, mention it to your health visitor or GP at your next check.',
    sourceName: 'Santé publique France (1000 premiers jours)',
    sourceUrl: 'https://www.1000-premiers-jours.fr/fr/les-etapes-du-developpement-de-bebe',
    sourceCountry: 'France',
    isWeeklyFeature: true,
  },
  {
    day: 79,
    title: 'Second vaccinations are due at 12 weeks',
    tip: 'At around 12 weeks, your baby is due their second 6-in-1 dose, a second and final rotavirus dose, and the pneumococcal vaccine, protecting against serious illnesses like meningitis and pneumonia. Depending on your baby\'s birth date, the MenB vaccine may also be given now rather than at 16 weeks under recent schedule changes. As before, some mild unsettledness or fever afterwards is normal — your health visitor or GP can advise on infant paracetamol if needed.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/vaccinations/nhs-vaccinations-and-when-to-have-them/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 80,
    title: 'Hold off on solid foods a little longer',
    tip: 'Even though your baby may seem curious about your food, solids aren\'t recommended before around six months, regardless of what packaging on some baby foods suggests. Breast milk or formula still provides everything they need nutritionally, while giving their gut more time to mature. Starting solids early doesn\'t help babies sleep through the night either, so there\'s no rush on that front.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/baby/weaning-and-feeding/babys-first-solid-foods/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 81,
    title: 'Tummy time is building real strength now',
    tip: 'By around three months, many babies can push up on their forearms during tummy time and hold their head steadier for longer, both important steps toward rolling later on. If your baby still resists it, keep sessions short, frequent and playful — get down on the floor with them to make it more engaging. Their tolerance for tummy time tends to jump noticeably around this age.',
    sourceName: 'NHS (UK)',
    sourceUrl: 'https://www.nhs.uk/best-start-in-life/baby/baby-moves/',
    sourceCountry: 'UK',
    isWeeklyFeature: false,
  },
  {
    day: 82,
    title: 'A steadier sleep rhythm is emerging',
    tip: 'Around three months, many babies start settling into a more predictable pattern, sleeping roughly 14-15 hours across the day with longer nighttime stretches — though waking once or twice to feed is still normal. This is a good age to start a simple, consistent bedtime ritual, since babies respond well to predictability from now on. Don\'t worry if your baby doesn\'t fit this pattern exactly; it\'s a general guide, not a rulebook.',
    sourceName: 'Sundhed.dk (Denmark)',
    sourceUrl: 'https://www.sundhed.dk/borger/patienthaandbogen/boern/om-boern/det-nyfoedte-barn/babyer-og-soevn/',
    sourceCountry: 'Denmark',
    isWeeklyFeature: false,
  },
  {
    day: 83,
    title: 'Enjoy the giggles and interactive play',
    tip: 'By three months, many babies are laughing, cooing back at you and clearly enjoying simple interactive games like peekaboo or gentle tickles. They\'re also getting better at recognising familiar faces and voices, which is why they may light up more for you than for a stranger. These playful exchanges are doing real developmental work, not just being fun.',
    sourceName: 'AEPED (Spain)',
    sourceUrl: 'https://www.aeped.es/enfamilia/salud-en-familia/bebe-2-4-meses',
    sourceCountry: 'Spain',
    isWeeklyFeature: false,
  },
  {
    day: 84,
    title: 'Start thinking ahead about childcare',
    tip: 'If you\'re planning a return to work, it\'s worth starting to research childcare options now — nurseries, childminders and family day care all tend to have waiting lists, so early planning gives you more choice. Talk to your employer and your partner together about timing and how you\'ll share the transition. Even if your return is still months away, a little groundwork now avoids a last-minute scramble.',
    sourceName: 'BZgA / familienplanung.de (Germany)',
    sourceUrl: 'https://www.familienplanung.de/schwangerschaft/familie-und-beruf/die-richtige-betreuung-fuer-ihr-kind/',
    sourceCountry: 'Germany',
    isWeeklyFeature: false,
  },
];
